feat: check sale prices before sending meta transactions
decentraland/transactions-server pull request #79
Opened 2022-04-13 15:56 UTC by nicosantangelo

Closes #80

2022-04-13 17:43 UTC, nachomazzara requested changes
Great work Nico!

2022-04-13 17:43 UTC, nachomazzara commented on src/logic/transaction.ts
> +export function getSalePrice(
What do you think of moving this to a different utils file like I mentioned above?

2022-04-13 17:43 UTC, nachomazzara commented on src/logic/transaction.ts
> +  const minPrice = await config.requireNumber('MIN_SALE_VALUE')
I would move all of this logic to a specific validator file like
`saleValidator.ts` and call it:

```
Sales.validateTx(tx)
```

2022-04-19 20:07 UTC, LautaroPetaccio requested changes

2022-04-20 01:29 UTC, nicosantangelo commented on src/ports/transaction/validation/checkSalePrice.ts
> +        const { _price } = decodeFunctionData(
It's the actual param from the bid contract :( could do { _price: price } if it looks better but can't really change it

2022-04-20 01:34 UTC, nicosantangelo commented on src/ports/transaction/validation/checkQuota.ts
> +  if (dbResult.count >= maxTransactionsPerDay) {
Just checked and it's a `number`! that's because we're using sqlite here and not pg. Good catch tho

2022-04-20 15:23 UTC, LautaroPetaccio approved these changes

2022-04-20 15:26 UTC, merged